[package]
name = "step_3_9"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive", "env"] }
config = "0.14"
humantime-serde = "1.1"
humantime = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
